### ISSUE TITLE
[BUG] Font on task card is larger when language is tz_sw

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/parenting-app-ui#2027]
**Describe the bug**
The font size of the text on a task card is bigger when the language is set to `tz_sw` than when it is `tz_en`. The size of English is correct.

**App version**
v0.16.18 `plh_tz`

**To Reproduce**
https://plh-tz.web.app/template/task_card
Change field `_app_language` between `tz_sw` and `tz_en` (+ refresh browser tab) and observe the difference

**Template Name**
[task_card](https://docs.google.com/spreadsheets/d/1WGXQpDIzsS-FbDX_aLXJ4geT03Uqjdc4Fm4m2C2W2fY/edit#gid=1983421448)

**Screenshots and videos**

[screen-capture (59).webm](https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/572891c0-ad1c-4948-9d5d-83a1d1df54ac)

**Comment by esmeetewinkel** [comment]
The style seems to be not inherited more generally, also the image moves to the other side (see screenshots) 

<img width="209" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/9a634363-cd46-4843-a123-52478b522914">
<img width="208" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/f6b2e042-70af-4501-aa19-3e3080fc3f01">

**Comment by jfmcquade** [comment]
This was a puzzling error but your assessment was right: `variant: button` isn't being set in the case that the language is `tz_sw`. That's because the "button" string that's being passed as the `variant` parameter is being translated.

Looking at the [task_card](https://docs.google.com/spreadsheets/d/1WGXQpDIzsS-FbDX_aLXJ4geT03Uqjdc4Fm4m2C2W2fY/edit#gid=1983421448) template, line 18 is missing a "TRUE" in the "exclude_from_translation", so I think adding that in should fix the issue.

**Comment by esmeetewinkel** [comment]
Ah, thanks Johnny, I didn't think of that. Makes sense.

Actually just setting "exclude_from_translation" to TRUE does not resolve the issue - this just prevents (this instance of) the word button to be added to the list of translatable strings. I also needed to remove the word button and its translation from the Swahili dictionary. Not so much of a problem in this case, I don't think the word button is used as a string that needs translation.  But something to keep in mind going forward that we cannot use parameter values that need to stay untranslated but are also translatable strings. 

<img width="206" alt="image" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/74557272/d75a0f5f-5059-43d0-a179-a9614e47e778">
